
[phases.setup]
# Explicitly specify the required system packages.
system = ["python3", "gcc"]

[phases.build]
# Install dependencies inside a virtual environment.
cmds = [
    "python -m venv .venv",
    ". .venv/bin/activate",
    "pip install -r requirements.txt"
]

[phases.start]
# Specify the start command using gunicorn.
cmd = ".venv/bin/gunicorn bulkup:app --bind 0.0.0.0:$PORT"
